config/routes.rb
Rails.application.routes.draw do
  constraints ->  request { request.session["warden.user.user.key"].present? } do
    root "outputs#index"
  end

  root 'toppages#index'

  resources :outputs
  get 'output_search', to: 'outputs#search'
  resources :likes, only: %i[create destroy]
  resources :action_plans
  resources :meetings, shallow: true do
    resources :messages
  end
  get 'meeting_search', to: 'meetings#search'
  resources :requestings, only: %i[create destroy]
  resources :participants, only: %i[create destroy]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]
  resources :books, only: %i[create show], shallow: true do
    collection do
      get :search
    end
  end
  
  resources :users, only: [:show]
  resource :profile, only: %i[index edit update]
  resources :notifications do
    resource :read, only: %i[create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  meeting_id :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_messages_on_meeting_id  (meeting_id)
#  index_messages_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (meeting_id => meetings.id)
#  fk_rails_...  (user_id => users.id)
#
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
  has_one :notification, as: :notifiable, dependent: :destroy

  validates :body, presence: true

  after_create_commit :create_notifications

  private

  def create_notifications
    Notification.create(notifiable: self, user: meeting.user) unless self.user == meeting.user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = current_user.messages.build(message_params)
    @message.save
  end

  def edit
    @message = current_user.messages.find(params[:id])
  end

  def update
    @message = current_user.messages.find(params[:id])
    @message.update(message_update_params)
  end

  def destroy
    @message = current_user.messages.find(params[:id])
    @message.destroy!
  end

  private

  def message_params
    params.require(:message).permit(:body).merge(meeting_id: params[:meeting_id])
  end

  def message_update_params
    params.require(:message).permit(:body)
  end
end

app/views/messages/_form.html.slim
= form_with model: [meeting, message], remote: true do |f|
  .row 
    .col
      = f.text_field :body, class: 'input-message-body form-control message-form', placeholder: 'メッセージ'
    .col
      = f.submit '投稿', class: 'btn btn-info btn-raised rounded btn-sm message-button'

app/views/messages/_message.html.slim
div id="message-#{message.id}"
  .row
    .col-sm-8
      - if message.user.avatar.present?
        = image_tag message.user.avatar.url, size: '30x30', class: 'rounded-circle mr-1' 
      - else 
        i.fas.fa-user
      = message.user.username 
      = " #{message.body}"
    .col-sm-4
      - if current_user&.own?(message)
        = link_to message_path(message), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'}, remote: true do
          = icon 'far', 'trash-alt', class: 'fa-sm delete-message-button'
        = link_to edit_message_path(message), remote: true do 
          = icon 'far', 'edit', class: 'fa-sm edit-message-button'

app/views/messages/_messages.html.slim
.messages-box
  = render messages

app/views/messages/_modal_form.html.slim
.modal#message-edit-modal 
  .modal-dialog 
    .modal-content
      .modal-header
        h5.modal-title メッセージ編集
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body
        = render 'form', meeting: nil, message: message

app/views/messages/create.js.slim
| $('.messages-box').prepend("#{j render('messages/message', message: @message)}");
| $('.input-message-body').val('');

app/views/messages/destroy.js.slim
| $('#message-#{@message.id}').remove()

app/views/messages/edit.js.slim
| $('#modal-container').html("#{j render('modal_form', message: @message)}");
| $('#message-edit-modal').modal('show');

app/views/messages/update.js.slim
| $("#message-#{@message.id}").html("#{j render('messages/message', message: @message)}");
| $("#message-edit-modal").modal('hide');