config/routes.rb
Rails.application.routes.draw do
  constraints ->  request { request.session["warden.user.user.key"].present? } do
    root "outputs#index"
  end

  root 'toppages#index'

  resources :outputs
  get 'output_search', to: 'outputs#search'
  resources :likes, only: %i[create destroy]
  resources :action_plans
  resources :meetings, shallow: true do
    resources :messages
  end
  get 'meeting_search', to: 'meetings#search'
  resources :requestings, only: %i[create destroy]
  resources :participants, only: %i[create destroy]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]
  resources :books, only: %i[create show], shallow: true do
    collection do
      get :search
    end
  end
  
  resources :users, only: [:show]
  resource :profile, only: %i[index edit update]
  resources :notifications do
    resource :read, only: %i[create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  
end

app/models/meeting.rb
require 'date'
# == Schema Information
#
# Table name: meetings
#
#  id          :bigint           not null, primary key
#  capacity    :integer          not null
#  date        :datetime         not null
#  description :text(65535)      not null
#  open        :boolean          default(TRUE), not null
#  title       :string(255)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_meetings_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :requestings, dependent: :destroy
  has_many :requesting_users, through: :requestings, source: :user
  has_many :participants, dependent: :destroy
  has_many :participanting_users, through: :participants, source: :user
  has_many :messages, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :date, presence: true
  validate :before_today
  def before_today
    errors.add(:date, 'に過去の日付は登録できません') if date.present? && (date < Date.today.to_time)
  end

  def permit?(user)
    participants.exists?(user_id: user.id)
  end

  def permit(user)
    participanting_users << user
  end

  def after_now?
    date > Date.today.to_time
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @meetings = Meeting.all.includes(:participanting_users, :user).page(params[:page]).per(10).order(date: :desc)
    @q = Meeting.ransack(params[:q])
  end

  def search
    @q = Meeting.search(search_params)
    @meetings = @q.result(distinct: true)
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)
    if @meeting.save
      redirect_to meetings_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def edit
    @meeting = current_user.meetings.find(params[:id])
  end

  def update
    @meeting = current_user.meetings.find(params[:id])
    if @meeting.update(meeting_params)
      redirect_to meeting_path(@meeting), success: '更新しました'
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @meeting = current_user.meetings.find(params[:id])
    @meeting.destroy!
    redirect_to meetings_path, success: '削除しました'
  end

  def show
    @meeting = Meeting.find(params[:id])
    @messages = @meeting.messages
    @message = Message.new
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :description, :date, :capacity)
  end

  def search_params
    params.require(:q).permit(:title_cont)
  end
end

app/views/meetings/_form.html.slim
= render 'shared/error_messages', object: meeting
.meeting-form-container
  = form_with model: meeting, local: true do |f|
    .form-group
      = f.text_field :title, class: 'form-control meeting-title-form', placeholder: 'タイトル', id: 'title_form'
    .form-group
      = f.text_area :description, class: 'form-control meeting-form', placeholder: '詳細', id: 'description_form'
    .row
      .form-group.col-6
        = f.number_field :capacity, class: 'form-control meeting-form', placeholder: '人数', id: 'capacity_form'
      .form-group.col-6
        = f.datetime_field :date, class: 'form-control meeting-form', placeholder: '開催日', id: 'date_form'
    = f.submit '投稿', class: 'btn btn-info btn-raised rounded'

app/views/meetings/_new_participant.html.slim
- if user
  - if user.avatar.present?
    = image_tag user.avatar.url, size: '20x20', class: 'rounded-circle mr-1' 
  - else 
    i.fas.fa-user
  = user.username
  = "の参加を許可しました"

app/views/meetings/_permit.html.slim
- if requesting_user.avatar.present?
  = image_tag requesting_user.avatar.url, size: '30x30', class: 'rounded-circle mr-1'
= requesting_user.username
= link_to '参加許可', participants_path(user_id: requesting_user.id, meeting_id: meeting.id), class: 'btn btn-outline-info btn-raised rounded mr-2 permit-button btn-sm', method: :post, remote: true
= link_to '参加拒否', requesting_path(requesting_user.requestings.find_by(meeting_id: meeting.id), user_id: requesting_user.id), class: 'btn btn-outline-danger btn-raised rounded reject-button btn-sm', method: :delete, remote: true

app/views/meetings/_permit_area.html.slim
div id="permit_area-#{requesting_user.id}"
  - if !meeting.permit?(requesting_user)
    = render 'permit', meeting: meeting, requesting_user: requesting_user

app/views/meetings/_reject_user.html.slim
- if user
  - if user.avatar.present?
    = image_tag user.avatar.url, size: '20x20', class: 'rounded-circle mr-1' 
  - else 
    i.fas.fa-user
  = user.username
  = "の参加を拒否しました"

app/views/meetings/_request.html.slim
- if meeting.capacity <= meeting.participanting_users.size
  = "定員に達しました"
- else
  = link_to '参加申請', requestings_path(meeting_id: meeting.id), class: 'btn btn-outline-info btn-raised rounded request-button', method: :post, remote: true 

app/views/meetings/_request_area.html.slim
- if !current_user.participant?(meeting)
  div id="request_area-#{meeting.id}"
    - if current_user.request?(meeting)
      = render 'unrequest', meeting: meeting 
    - else 
      = render 'request', meeting: meeting

app/views/meetings/_search_form.html.slim
= search_form_for(@q, url:meeting_search_path) do |f|
  .row
    .col
      = f.search_field :title_cont, class: 'form-control', placeholder: 'キーワード'
    .col
      = f.submit 'search', class: 'btn btn-info btn-raised rounded'

app/views/meetings/_unrequest.html.slim
= link_to '申請取り消し', requesting_path(current_user.requestings.find_by(meeting_id: meeting.id), user_id: current_user.id), class: 'btn btn-info btn-raised rounded unrequest-button', method: :delete, remote: true

app/views/meetings/edit.html.slim
= render 'form', meeting: @meeting

app/views/meetings/index.html.slim
.meetings-container
  h6
    | 読書会検索
  .search-form = render 'search_form'
  .row
    - @meetings.each do |meeting|
      .col-md-12
        .card.meetings-card
          .card-body 
            .row
              .col-4
                - if meeting.user.avatar.present?
                  = image_tag meeting.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1' 
                - else 
                  i.fas.fa-user
                = meeting.user.username
              .col-8
                = link_to meeting_path(meeting)
                  .card-title = meeting.title
                - if !meeting.after_now?
                  = '※終了しました'
              .meetings-body = meeting.description[0,100]
              .meetings-info = "参加人数: #{meeting.participanting_users.size}人/#{meeting.capacity}人"
              .meeting-date = "開催日: #{meeting.date.to_s(:datetime)}"
  = paginate @meetings

= link_to new_meeting_path do
  .new-btn
    i.fa.fa-plus

app/views/meetings/new.html.slim
= render 'form', meeting: @meeting

app/views/meetings/search.html.slim
.meetings-container
  h6 
    | 検索結果

  .row
    - @meetings.each do |meeting|
      .col-md-12
        .card.meetings-card
          .card-body 
            .row
              .col-4
                - if meeting.user.avatar.present?
                  = image_tag meeting.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1' 
                - else 
                  i.fas.fa-user
                = meeting.user.username
              .col-8
                = link_to meeting_path(meeting)
                  .card-title = meeting.title
                - if !meeting.after_now?
                  = '※終了しました'
              .meetings-body = meeting.description[0,100]
              .meetings-info = "参加人数: #{meeting.participanting_users.size}人/#{meeting.capacity}人"
              .meeting-date = "開催日: #{meeting.date.to_s(:datetime)}"

app/views/meetings/show.html.slim
.card.meetings-container
  .meetings-wrapper
    .row.meeting-header
      .col-4
        = link_to user_path(@meeting.user)
          - if @meeting.user.avatar.present?
            = image_tag @meeting.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1' 
          - else 
            i.fas.fa-user
          = @meeting.user.username
      .col-8
        .card-title = @meeting.title
    .meeting-content = @meeting.description
    .meeting-info = "参加人数: #{@meeting.participanting_users.size}人/#{@meeting.capacity}人"
    .meeting-info 
      = '参加者一覧: '
      = render 'new_participant', user: nil
      = render 'reject_user', user: nil
      - @meeting.participanting_users.each do |permited_user|
        = link_to user_path(permited_user)
          - if permited_user.avatar.present?
            = image_tag permited_user.avatar.url, size: '20x20', class: 'rounded-circle mr-1'
          = "#{permited_user.username} "
    
    - if current_user&.own?(@meeting)
      - if @meeting.after_now?
        .meeting-info = "参加申請一覧:"
        - @meeting.requesting_users.each do |requesting_user|
          = render 'permit_area', meeting: @meeting, requesting_user: requesting_user

      .meeting-buttons 
        = link_to edit_meeting_path(@meeting), class: 'edit-button' do
          = icon 'far', 'edit'
        = link_to meeting_path(@meeting), class: 'delete-button', method: :delete, data: { confirm: '本当に削除しますか？' } do
          = icon 'far', 'trash-alt'
    - elsif current_user
      - if @meeting.after_now?
        = render 'request_area', meeting: @meeting
    
    - if current_user&.own?(@meeting) || current_user&.participant?(@meeting)
      .messages
        = 'メッセージ'
        = render 'messages/messages', messages: @messages
      hr.m-0
      .post-message.p-3
        = render 'messages/form', meeting: @meeting, message: @message

      .twitter-share-link
        = link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank'
          i.fab.fa-twitter = "Twitterでシェア"
    = "開催日時: #{@meeting.date.to_s(:datetime)}"
      