config/routes.rb
Rails.application.routes.draw do
  constraints ->  request { request.session["warden.user.user.key"].present? } do
    root "outputs#index"
  end

  root 'toppages#index'

  resources :outputs
  get 'output_search', to: 'outputs#search'
  resources :likes, only: %i[create destroy]
  resources :action_plans
  resources :meetings, shallow: true do
    resources :messages
  end
  get 'meeting_search', to: 'meetings#search'
  resources :requestings, only: %i[create destroy]
  resources :participants, only: %i[create destroy]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]
  resources :books, only: %i[create show], shallow: true do
    collection do
      get :search
    end
  end
  
  resources :users, only: [:show]
  resource :profile, only: %i[index edit update]
  resources :notifications do
    resource :read, only: %i[create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  avatar                 :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  provider               :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  uid                    :string(255)
#  username               :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[twitter]

  mount_uploader :avatar, AvatarUploader

  has_many :outputs, dependent: :destroy
  has_many :action_plans, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_outputs, through: :likes, source: :output
  has_many :meetings, dependent: :destroy
  has_many :requestings, dependent: :destroy
  has_many :request_meetings, through: :requestings, source: :meeting
  has_many :participants, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :notifications, dependent: :destroy

  # VALID_PASSWORD_REGEX = /^[0-9a-zA-Z]*$/
  # validates :password, format: {with: VALID_PASSWORD_REGEX}

  def self.find_or_create_from_oauth(auth)
    User.find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.username = auth.info.nickname
      user.avatar = auth.info.image
      user.email = User.dummy_email(auth)
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def own?(object)
    id == object.user_id
  end

  def like?(output)
    likes.exists?(output_id: output.id)
  end

  def like(output)
    like_outputs << output
  end

  def unlike(output)
    like_outputs.destroy(output)
  end

  def request?(meeting)
    requestings.exists?(meeting_id: meeting.id)
  end

  def request(meeting)
    request_meetings << meeting
  end

  def unrequest(meeting)
    request_meetings.destroy(meeting)
  end

  def participant?(meeting)
    participants.exists?(meeting_id: meeting.id)
  end

  def follow(other_user)
    followings << other_user
  end

  def unfollow(other_user)
    followings.destroy(other_user)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = 'ゲストさん'
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_or_create_from_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      session[:user_id] = @user.id
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_follow.html.slim
= link_to relationships_path(followed_id: user.id), class: 'btn btn-outline-info btn-raised rounded follow-button', method: :post, remote: true do 
  | フォロー
  

app/views/users/_follow_area.html.slim
div id="follow-area-#{user.id}"
  - if current_user.following?(user)
    = render 'unfollow', user: user 
  - else 
    = render 'follow', user: user 
    

app/views/users/_unfollow.html.slim
= link_to relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), class: 'btn btn-info btn-raised unfollow-button', method: :delete, remote: true do 
  | アンフォロー

app/views/users/_user_contents.html.slim
#accordionMypage.accordion
  .card
    #headingOne.card-header
      h5.mb-0
        button.btn.btn-link.collapsed[type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"]
          | アウトプット
    #collapseOne.collapse[aria-labelledby="headingOne" data-parent="#accordionMypage"]
      .card-body
        - if @user.outputs.empty?
          = 'まだ投稿はありません'
        - else
          - @user.outputs.each do |output|
              .card
                = link_to output_path(output)
                  - if output.book_image.present?
                    = image_tag output.book_image
                  = output.title
  - if current_user.id == @user.id
    .card
      #headingTwo.card-header
        h5.mb-0
          button.btn.btn-link.collapsed[type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"]
            |  アクションプラン
      #collapseTwo.collapse[aria-labelledby="headingTwo" data-parent="#accordionMypage"]
        .card-body
          - if @user.action_plans.empty?
            = 'まだ投稿はありません'
          - else 
            - @user.action_plans.each do |action_plan|
                .card
                  = link_to action_plan_path(action_plan)
                    - if action_plan.book_image.present?
                      = image_tag action_plan.book_image
                    .font-small = action_plan.action_content
  .card
    #headingThree.card-header
      h5.mb-0
        button.btn.btn-link.collapsed[type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree"]
          |  読書会
    #collapseThree.collapse[aria-labelledby="headingThree" data-parent="#accordionMypage"]
      .card-body
        - if @user.meetings.empty?
          = 'まだ投稿はありません'
        - else
          - @user.meetings.each do |meeting|
              .card
                = link_to meeting_path(meeting)
                  = meeting.title

app/views/users/_user_follow.html.slim
.row 
  .col 
    #multiCollapseFollow.collapse.multi-collapse 
      - if user.followings.present?
        - user.followings.each do |following|
          = link_to user_path(following)
            .users
              - if following.avatar.present?
                = image_tag following.avatar.url, size: '20x20', class: 'rounded-circle mr-1'
              - else 
                i.fas.fa-user
              = following.username
      - else
        .fontsize-sm = "フォローしているユーザーはいません"
  .col 
    #multiCollapseFollower.collapse.multi-collapse
      - if user.followers.present?
        - user.followers.each do |follower|
          = link_to user_path(follower)
            .users
              - if follower.avatar.present?
                = image_tag follower.avatar.url, size: '20x20', class: 'rounded-circle mr-1'
              - else 
                i.fas.fa-user
              = follower.username
      - else
        .fontsize-sm = "フォロワーはいません"

app/views/users/show.html.slim
.mypage-container
  .row.mypage-top
    .col-3
      - if @user.avatar.present?
        = image_tag @user.avatar.url, size: '100x100', class: 'rounded-circle mr-1'
      - else 
        i.fas.fa-user.no-image
    .col-9
      .row 
        .col-6.mypage-name
          = @user.username
        .col-6.mypage-btn
          - if current_user.id == @user.id
            = link_to 'プロフィール編集', edit_profile_path(@user.id)
            .dropdown.notification-icon 
              a#dropdownMenuButton.nav-link.position-relative.notification-button href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
                = render 'shared/unread_badge'
                = ' 通知'
              #header-notifications.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
                = render 'shared/notifications'
          - elsif current_user 
            = render 'follow_area', user: @user
      p
        = @user.followings.size
        a.btn.mypage-btn aria-controls="multiCollapseFollow" aria-expanded="false" data-toggle="collapse" href="#multiCollapseFollow" role="button" フォロー
        = @user.followers.size
        a.btn.mypage-btn aria-controls="multiCollapseFollower" aria-expanded="false" data-toggle="collapse" href="#multiCollapseFollower" role="button" フォロワー

  = render 'user_follow', user: @user
  = render 'user_contents', user: @user