config/routes.rb
Rails.application.routes.draw do
  constraints ->  request { request.session["warden.user.user.key"].present? } do
    root "outputs#index"
  end

  root 'toppages#index'

  resources :outputs
  get 'output_search', to: 'outputs#search'
  resources :likes, only: %i[create destroy]
  resources :action_plans
  resources :meetings, shallow: true do
    resources :messages
  end
  get 'meeting_search', to: 'meetings#search'
  resources :requestings, only: %i[create destroy]
  resources :participants, only: %i[create destroy]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :relationships, only: %i[create destroy]
  resources :books, only: %i[create show], shallow: true do
    collection do
      get :search
    end
  end
  
  resources :users, only: [:show]
  resource :profile, only: %i[index edit update]
  resources :notifications do
    resource :read, only: %i[create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  
end

app/views/shared/_before_login_header.html.slim
nav#mainNav.navbar.navbar-expand-lg.navbar-light.fixed-top
  .container
    nav.navbar-light
      = link_to 'Lead Read', root_path, class: 'navbar-brand'
    button.navbar-toggler.navbar-toggler-right[type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"]
      |  Menu 
      i.fas.fa-bars
    #navbarResponsive.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li.nav-item
          a.nav-link[href="about.html"]
            = link_to new_user_registration_path
              i.fas.fa-user-plus = " ユーザー登録"
        li.nav-item
          a.nav-link[href="post.html"]
            = link_to new_user_session_path
              i.fas.fa-sign-in-alt = " ログイン"

app/views/shared/_error_messages.html.slim
- if object&.errors&.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
/ .notifications
/   - flash.each do |key, value|
/     = content_tag(:div, value, class: "flash flash__#{key}")

.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/shared/_followed_me.html.slim
.dropdown-item.border-bottom.follow-notification
  - if notification.notifiable.follower.avatar.present?
    = image_tag notification.notifiable.follower.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  - else 
    i.fas.fa-user
  object 
    = link_to notification.notifiable.follower.username, user_path(notification.notifiable.follower)
  | があなたをフォローしました
  .ml-auto
    = l notification.created_at, format: :short
    object
      = link_to ' ✖️', notification_read_path(notification), class: "#{'read' if notification.read?}", method: :post 

app/views/shared/_header.html.slim
nav#mainNav.navbar.navbar-expand-lg.navbar-light.fixed-top.header
  .container
    nav.navbar-light
      = link_to 'Lead Read', user_path(current_user.id), class: 'navbar-brand'
    button.navbar-toggler.navbar-toggler-right[type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"]
      |  Menu 
      i.fas.fa-bars
    #navbarResponsive.collapse.navbar-collapse
      ul.navbar-nav.ml-auto   
        li.nav-item
          a.nav-link
            = link_to outputs_path  
              i.fas.fa-clipboard-list = " アウトプット"
        li.nav-item
          a.nav-link
            = link_to action_plans_path  
              i.fas.fa-clipboard-list = " アクションプラン"
        li.nav-item
          a.nav-link
            = link_to meetings_path
              i.fas.fa-users = " 読書会"
        li.nav-item
          a.nav-link
            = link_to user_path(current_user.id)
              i.fas.fa-smile = " マイページ"
        li.nav-item
          a.nav-link
            = link_to destroy_user_session_path, class: 'logout-button', method: :delete
              i.fas.fa-sign-out-alt = " ログアウト"
    

app/views/shared/_header_notifications.html.slim
- if current_user.notifications.unread.present?
  - current_user.notifications.unread.recent(10).each do |notification|
    = render "shared/#{notification.call_appropriate_partial}", notification: notification
  - if current_user.notifications.count > 10
    = link_to 'すべてみる', notifications_path, class: 'dropdown-item justify-content-center'
- else 
  .dropdown-item 
    = "お知らせはありません"

app/views/shared/_liked_to_own_output.html.slim
.dropdown-item.border-bottom.like-notification
  - if notification.notifiable.user.avatar.present?
    = image_tag notification.notifiable.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  - else 
    i.fas.fa-user
  object 
    = link_to notification.notifiable.user.username, user_path(notification.notifiable.user)
  | があなたの
  object 
    = link_to 'アウトプット', output_path(notification.notifiable.output)
  | にいいねしました
  .ml-auto
    = l notification.created_at, format: :short
  object
    = link_to ' ✖️', notification_read_path(notification), class: "#{'read' if notification.read?}", method: :post 

app/views/shared/_message_to_own_meeting.html.slim
.dropdown-item.border-bottom.message-notification
  - if notification.notifiable.user.avatar.present?
    = image_tag notification.notifiable.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  - else 
    i.fas.fa-user
  object
    = link_to notification.notifiable.user.username, user_path(notification.notifiable.user)
  | があなたの
  object 
    = link_to '読書会', meeting_path(notification.notifiable.meeting)
  | にメッセージを送信しました
  .ml-auto
    = l notification.created_at, format: :short
    object
      = link_to ' ✖️', notification_read_path(notification), class: "#{'read' if notification.read?}", method: :post 
        

app/views/shared/_modal.html.slim
#modal-container

app/views/shared/_notifications.html.slim
- if current_user.notifications.unread.present?
  - current_user.notifications.unread.recent(10).each do |notification|
    = render "shared/#{notification.call_appropriate_partial}", notification: notification
- else 
  .dropdown-item 
    = "お知らせはありません"

app/views/shared/_permitted_me.html.slim
.dropdown-item.border-bottom.permit-notification
  object
    = link_to '読書会', meeting_path(notification.notifiable.meeting)
  | への参加を許可されました
  .ml-auto
    = l notification.created_at, format: :short
    object
      = link_to ' ✖️', notification_read_path(notification), class: "#{'read' if notification.read?}", method: :post 

app/views/shared/_requested_to_own_meeting.html.slim
.dropdown-item.border-bottom.request-notification
  - if notification.notifiable.user.avatar.present?
    = image_tag notification.notifiable.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  - else 
    i.fas.fa-user
  object
    = link_to notification.notifiable.user.username, user_path(notification.notifiable.user)
  | があなたの
  object 
    = link_to '読書会', meeting_path(notification.notifiable.meeting)
  | に参加申請を送りました
  .ml-auto
    = l notification.created_at, format: :short
    object
      = link_to ' ✖️', notification_read_path(notification), class: "#{'read' if notification.read?}", method: :post 

app/views/shared/_unread_badge.html.slim
- if current_user.notifications.unread.size > 0
  span.fa-stack
    i.far.fa-bell.fa-sm.fa-stack-2x style="font-size: 1.3em;" 
    i.fas.fa-circle.n-circle.fa-stack-1x style="font-size: 0.8em"
- else 
  i.far.fa-bell.fa-sm style="font-size: 1.3em;" 